### ISSUE TITLE
Fix the input masking problem

### ISSUE THREAD

**Issue by martndemus** [DockYard/ember-one-way-controls#100]
cc @miguelcobain

**Comment by miguelcobain** [comment]
To make this a bit more clear, the problem is that input isn't "true" ddau.

Example:
```hbs
{{one-way-input value update=(action "updateValue")}}
```
```js
updateValue() {
  this.set('value', '123123');
}
```

Here I intend to set the input to a constant value, regardless of what the user types in.
This is the simplest case, just for illustration purposes. You can imagine the app "overriding" what the user typed. e.g input masks, max chars, format the input in some way, etc.

In ember-paper we solved this by internally managing the input value ourselves, and re-syncing i nthe next run loop after we call the action.
The key parts are:
  - Encapsulate the value setting logic: https://github.com/miguelcobain/ember-paper/blob/master/addon/components/paper-input.js#L222-L226
  - Set the value once rendered: https://github.com/miguelcobain/ember-paper/blob/master/addon/components/paper-input.js#L160
  - The action sending part: https://github.com/miguelcobain/ember-paper/blob/master/addon/components/paper-input.js#L230-L234

Note that `notifyPropertyChange` won't work here.
