### ISSUE TITLE
Uncaught Error: Could not find module ember-metal/streams/utils

### ISSUE THREAD

**Issue by lolmaus** [DockYard/ember-one-way-controls#145]
My Ember 2.11.0 app crashes with this error.

It is caused by the fact that `ember-one-way-controls` includes the [ember-get-helper](https://github.com/jmurphyau/ember-get-helper) addon, which is officially "deprecated and support for Ember 2.0 will not be maintained".

**Comment by rwjblue** [comment]
ember-get-helper does nothing if being included in an app with ember 2.0 or higher (see https://github.com/jmurphyau/ember-get-helper/blob/master/index.js for how that is done).

The thing we need to do is update ember-her-helper to allow ember-source from NPM. I can update shortly...

**Comment by fastfedora** [comment]
I'm having the same error. Since `ember-get-helper` is not being maintained, hasn't had a commit for over 8 months and still has the PR open that was submitted over a month ago, is it possible to just remove `ember-get-helper` from `ember-one-way-controls`? With the version bump to 2.0.0, it seems reasonable to make it compatible only with Ember 2.x.

Right now I'm blocked from using `ember-form-for` because it depends on this project, which depends on `ember-get-helper`, which won't work in Ember 2.10.

**Comment by cowboyd** [comment]
I'm not getting an error, but an annoying deprecation warning: 

```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-get-helper`
    at Function.Addon.lookup (node_modules/ember-cli/lib/models/addon.js:1006:27)
```

**Comment by martndemus** [comment]
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.
